instance_class: F2
runtime: python310

env_variables:
  GSHEETS_PLAID_RESTRICTIONS_ENABLED: 1

handlers:
- url: /static
  static_dir: static
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
